/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemamedico.visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import sistemamedico.dao.PerguntaDAO;
import sistemamedico.dao.RespostaDAO;
import sistemamedico.modelo.Pergunta;

/**
 *
 * @author Nano
 */
public class Doenca extends javax.swing.JFrame {

    /**
     * Creates new form Doenca
     */
    public Doenca() {
        super("SisMedi - Doença");
        this.setContentPane(new JLabel(new ImageIcon(getClass().getResource("/imagens2/1.jpg"))));
        initComponents();
        setLocationRelativeTo(null); // Abre a janela no centro da tela
        setResizable(false); // Desactivando a opção de redimensionar
        setVisible(true); // Define a visibilidade da janela
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Desactivar o fecho ao clicar em x
        URL caminhoImagem = this.getClass().getClassLoader().getResource("imagens/estetoscopio.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
        
        carregarSintomas();
    }

     private void carregarSintomas()
    {
        listaSintomas.setModel(getSintomas());
    }
    
    private ListModel<String> getSintomas()
    {
        DefaultListModel<String> sintomas = new DefaultListModel<>();
        
        for (Pergunta p : PerguntaDAO.getPerguntas())
            sintomas.addElement(p.getValor());
        
        return sintomas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaSintomas = new javax.swing.JList<>();
        txtDoenca = new javax.swing.JTextField();
        btnSalvar1 = new javax.swing.JButton();
        btnEncerrar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaSintomas.setBackground(new java.awt.Color(17, 113, 108));
        jScrollPane2.setViewportView(listaSintomas);

        txtDoenca.setBackground(new java.awt.Color(17, 113, 108));

        btnSalvar1.setBackground(new java.awt.Color(17, 113, 108));
        btnSalvar1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnEncerrar1.setBackground(new java.awt.Color(17, 113, 108));
        btnEncerrar1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnEncerrar1.setText("Voltar");
        btnEncerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrar1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel2.setText("Nova Doença");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estetoscopio.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel14))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEncerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDoenca)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrar1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Cadastro().setVisible(true);
    }//GEN-LAST:event_btnEncerrar1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // TODO add your handling code here:
               String nomeDoenca = txtDoenca.getText().trim().toLowerCase().replace(" ", "_");
        List<String> sintomas = listaSintomas.getSelectedValuesList();

        if(sintomas.size() == 0)
            JOptionPane.showMessageDialog( null, "Não selecionaste nenhum sintoma");
        else
        {
            Boolean existe = false;
            for(String nome : RespostaDAO.getNomesTodasPatologias())
            {    
                if(nome.equalsIgnoreCase(nomeDoenca))
                    existe = true;
            }

            if(existe)       
                JOptionPane.showMessageDialog( null, "A patalogia "+nomeDoenca+" já existe na base de conhecimento ");
            else
            {
                 RespostaDAO.inserirNovaregra(sintomas, nomeDoenca);
                JOptionPane.showMessageDialog( null, "Salvo com sucesso");
            }
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doenca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncerrar1;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaSintomas;
    private javax.swing.JTextField txtDoenca;
    // End of variables declaration//GEN-END:variables
}
